# Project Name
TARGET =  guitarpedal1590btest

# Sources
CPP_SOURCES = guitar_pedal_1590b_test.cpp guitar_pedal_1590b.cpp

# Library Locations
DAISYSP_DIR ?= /Users/kshep/Dev/DaisyExamples/DaisySP
LIBDAISY_DIR ?= /Users/kshep/Dev/DaisyExamples/libDaisy

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

