# Project Name
TARGET =  guitarpedal

# Sources
CPP_SOURCES = guitar_pedal.cpp Hardware-Modules/guitar_pedal_125b.cpp Hardware-Modules/guitar_pedal_1590b.cpp Effect-Modules/base_effect_module.cpp Effect-Modules/modulated_tremolo_module.cpp Effect-Modules/overdrive_module.cpp Effect-Modules/chorus_module.cpp Effect-Modules/autopan_module.cpp

# Library Locations
DAISYSP_DIR ?= /Users/kshep/Dev/DaisyExamples/DaisySP
LIBDAISY_DIR ?= /Users/kshep/Dev/DaisyExamples/libDaisy

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

